# Cấu hình auto scale cho api
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # Config here
  name: server-api-autoscaler
  # Config here
  namespace: demo-backend-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-api-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # 50% of the CPU of the node
        averageUtilization: 95
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 1500Mi