apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-api-autoscaler
  namespace: demo-backend-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-api-deployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 1200Mi