apiVersion: v1
kind: Service
metadata:
  name: demo-backend-api-service
  namespace: demo-backend-ns
spec:
  selector:
     app: server-api
  type: NodePort
  ports:
    - name: port-api
      port: 80
      targetPort: 5000
      nodePort: 31186